language: bash

services:
  - docker

env:
  matrix:
    - DRUPAL_VER=8 PHP_VER=7.1
    - DRUPAL_VER=8 PHP_VER=7.0
    - DRUPAL_VER=7 PHP_VER=7.1
    - DRUPAL_VER=7 PHP_VER=7.0
    - DRUPAL_VER=7 PHP_VER=5.6
    - DRUPAL_VER=6 PHP_VER=5.6
    - DRUPAL_VER=6 PHP_VER=5.3

script:
  - make test

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
    - docker-compose.yml
    - docker-sync.yml
    - docker.mk
    - .env
    - traefik.yml
  on:
    tags: true
